package tv.mapper.embellishcraft.building.block;

import java.util.Arrays;
import java.util.Map;
import java.util.stream.Collectors;

import org.apache.commons.lang3.tuple.Pair;

import net.minecraft.world.item.DyeColor;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.properties.BlockSetType;
import net.minecraft.world.level.material.MapColor;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredRegister;
import tv.mapper.embellishcraft.core.ECConstants;
import tv.mapper.embellishcraft.core.util.McWoods;
import tv.mapper.mapperbase.api.block.CustomBlock;
import tv.mapper.mapperbase.api.block.CustomDoorBlock;
import tv.mapper.mapperbase.api.block.CustomPressurePlateBlock;
import tv.mapper.mapperbase.api.block.CustomSlabBlock;
import tv.mapper.mapperbase.api.block.CustomStairBlock;
import tv.mapper.mapperbase.api.block.CustomWallBlock;
import tv.mapper.mapperbase.api.block.UpDownBlock;
import tv.mapper.mapperbase.api.block.tools.ToolTypes;

public class InitBuildingBlocks
{
    public static final DeferredRegister.Blocks BUILDING_BLOCK_REGISTRY = DeferredRegister.createBlocks(ECConstants.MODID);

    // Other bricks
    public static final DeferredBlock<CustomBlock> DARK_BRICKS = BUILDING_BLOCK_REGISTRY.register("dark_bricks", () -> new CustomBlock(Block.Properties.of().mapColor(MapColor.NETHER).sound(SoundType.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomStairBlock> DARK_BRICKS_STAIRS = BUILDING_BLOCK_REGISTRY.register("dark_bricks_stairs", () -> new CustomStairBlock(DARK_BRICKS.get().defaultBlockState(), Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomSlabBlock> DARK_BRICKS_SLAB = BUILDING_BLOCK_REGISTRY.register("dark_bricks_slab", () -> new CustomSlabBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomWallBlock> DARK_BRICKS_WALL = BUILDING_BLOCK_REGISTRY.register("dark_bricks_wall", () -> new CustomWallBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomPressurePlateBlock> DARK_BRICKS_PRESSURE_PLATE = BUILDING_BLOCK_REGISTRY.register("dark_bricks_pressure_plate", () -> new CustomPressurePlateBlock(BlockSetType.STONE, Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).noCollission().strength(1.5F, 6.0F), ToolTypes.PICKAXE));

    public static final DeferredBlock<CustomBlock> DARK_LARGE_BRICKS = BUILDING_BLOCK_REGISTRY.register("dark_large_bricks", () -> new CustomBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomStairBlock> DARK_LARGE_BRICKS_STAIRS = BUILDING_BLOCK_REGISTRY.register("dark_large_bricks_stairs", () -> new CustomStairBlock(DARK_LARGE_BRICKS.get().defaultBlockState(), Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomSlabBlock> DARK_LARGE_BRICKS_SLAB = BUILDING_BLOCK_REGISTRY.register("dark_large_bricks_slab", () -> new CustomSlabBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomWallBlock> DARK_LARGE_BRICKS_WALL = BUILDING_BLOCK_REGISTRY.register("dark_large_bricks_wall", () -> new CustomWallBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomPressurePlateBlock> DARK_LARGE_BRICKS_PRESSURE_PLATE = BUILDING_BLOCK_REGISTRY.register("dark_large_bricks_pressure_plate", () -> new CustomPressurePlateBlock(BlockSetType.STONE, Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).noCollission().strength(1.5F, 6.0F), ToolTypes.PICKAXE));

    public static final DeferredBlock<CustomBlock> OLD_BRICKS = BUILDING_BLOCK_REGISTRY.register("old_bricks", () -> new CustomBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomStairBlock> OLD_BRICKS_STAIRS = BUILDING_BLOCK_REGISTRY.register("old_bricks_stairs", () -> new CustomStairBlock(OLD_BRICKS.get().defaultBlockState(), Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomSlabBlock> OLD_BRICKS_SLAB = BUILDING_BLOCK_REGISTRY.register("old_bricks_slab", () -> new CustomSlabBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomWallBlock> OLD_BRICKS_WALL = BUILDING_BLOCK_REGISTRY.register("old_bricks_wall", () -> new CustomWallBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomPressurePlateBlock> OLD_BRICKS_PRESSURE_PLATE = BUILDING_BLOCK_REGISTRY.register("old_bricks_pressure_plate", () -> new CustomPressurePlateBlock(BlockSetType.STONE, Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).noCollission().strength(1.5F, 6.0F), ToolTypes.PICKAXE));

    public static final DeferredBlock<CustomBlock> OLD_LARGE_BRICKS = BUILDING_BLOCK_REGISTRY.register("old_large_bricks", () -> new CustomBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomStairBlock> OLD_LARGE_BRICKS_STAIRS = BUILDING_BLOCK_REGISTRY.register("old_large_bricks_stairs", () -> new CustomStairBlock(OLD_LARGE_BRICKS.get().defaultBlockState(), Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomSlabBlock> OLD_LARGE_BRICKS_SLAB = BUILDING_BLOCK_REGISTRY.register("old_large_bricks_slab", () -> new CustomSlabBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomWallBlock> OLD_LARGE_BRICKS_WALL = BUILDING_BLOCK_REGISTRY.register("old_large_bricks_wall", () -> new CustomWallBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomPressurePlateBlock> OLD_LARGE_BRICKS_PRESSURE_PLATE = BUILDING_BLOCK_REGISTRY.register("old_large_bricks_pressure_plate", () -> new CustomPressurePlateBlock(BlockSetType.STONE, Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).noCollission().strength(1.5F, 6.0F), ToolTypes.PICKAXE));

    public static final DeferredBlock<CustomBlock> WEARED_BRICKS = BUILDING_BLOCK_REGISTRY.register("weared_bricks", () -> new CustomBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomStairBlock> WEARED_BRICKS_STAIRS = BUILDING_BLOCK_REGISTRY.register("weared_bricks_stairs", () -> new CustomStairBlock(WEARED_BRICKS.get().defaultBlockState(), Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomSlabBlock> WEARED_BRICKS_SLAB = BUILDING_BLOCK_REGISTRY.register("weared_bricks_slab", () -> new CustomSlabBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomWallBlock> WEARED_BRICKS_WALL = BUILDING_BLOCK_REGISTRY.register("weared_bricks_wall", () -> new CustomWallBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomPressurePlateBlock> WEARED_BRICKS_PRESSURE_PLATE = BUILDING_BLOCK_REGISTRY.register("weared_bricks_pressure_plate", () -> new CustomPressurePlateBlock(BlockSetType.STONE, Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).noCollission().strength(1.5F, 6.0F), ToolTypes.PICKAXE));

    public static final DeferredBlock<CustomBlock> WEARED_LARGE_BRICKS = BUILDING_BLOCK_REGISTRY.register("weared_large_bricks", () -> new CustomBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomStairBlock> WEARED_LARGE_BRICKS_STAIRS = BUILDING_BLOCK_REGISTRY.register("weared_large_bricks_stairs", () -> new CustomStairBlock(WEARED_LARGE_BRICKS.get().defaultBlockState(), Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomSlabBlock> WEARED_LARGE_BRICKS_SLAB = BUILDING_BLOCK_REGISTRY.register("weared_large_bricks_slab", () -> new CustomSlabBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomWallBlock> WEARED_LARGE_BRICKS_WALL = BUILDING_BLOCK_REGISTRY.register("weared_large_bricks_wall", () -> new CustomWallBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomPressurePlateBlock> WEARED_LARGE_BRICKS_PRESSURE_PLATE = BUILDING_BLOCK_REGISTRY.register("weared_large_bricks_pressure_plate", () -> new CustomPressurePlateBlock(BlockSetType.STONE, Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.NETHER).noCollission().strength(1.5F, 6.0F), ToolTypes.PICKAXE));

    // Pavings
    public static final DeferredBlock<CustomBlock> CONCRETE_PAVING = BUILDING_BLOCK_REGISTRY.register("concrete_paving", () -> new CustomBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomStairBlock> CONCRETE_PAVING_STAIRS = BUILDING_BLOCK_REGISTRY.register("concrete_paving_stairs", () -> new CustomStairBlock(CONCRETE_PAVING.get().defaultBlockState(), Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomSlabBlock> CONCRETE_PAVING_SLAB = BUILDING_BLOCK_REGISTRY.register("concrete_paving_slab", () -> new CustomSlabBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomWallBlock> CONCRETE_PAVING_WALL = BUILDING_BLOCK_REGISTRY.register("concrete_paving_wall", () -> new CustomWallBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomPressurePlateBlock> CONCRETE_PAVING_PRESSURE_PLATE = BUILDING_BLOCK_REGISTRY.register("concrete_paving_pressure_plate", () -> new CustomPressurePlateBlock(BlockSetType.STONE, Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).noCollission().strength(1.5F, 6.0F), ToolTypes.PICKAXE));

    public static final DeferredBlock<CustomBlock> DAMAGED_PAVING = BUILDING_BLOCK_REGISTRY.register("damaged_paving", () -> new CustomBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomStairBlock> DAMAGED_PAVING_STAIRS = BUILDING_BLOCK_REGISTRY.register("damaged_paving_stairs", () -> new CustomStairBlock(DAMAGED_PAVING.get().defaultBlockState(), Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomSlabBlock> DAMAGED_PAVING_SLAB = BUILDING_BLOCK_REGISTRY.register("damaged_paving_slab", () -> new CustomSlabBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomWallBlock> DAMAGED_PAVING_WALL = BUILDING_BLOCK_REGISTRY.register("damaged_paving_wall", () -> new CustomWallBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomPressurePlateBlock> DAMAGED_PAVING_PRESSURE_PLATE = BUILDING_BLOCK_REGISTRY.register("damaged_paving_pressure_plate", () -> new CustomPressurePlateBlock(BlockSetType.STONE, Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).noCollission().strength(1.5F, 6.0F), ToolTypes.PICKAXE));

    public static final DeferredBlock<CustomBlock> DARK_CONCRETE_PAVING = BUILDING_BLOCK_REGISTRY.register("dark_concrete_paving", () -> new CustomBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.TERRACOTTA_BLACK).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomStairBlock> DARK_CONCRETE_PAVING_STAIRS = BUILDING_BLOCK_REGISTRY.register("dark_concrete_paving_stairs", () -> new CustomStairBlock(DARK_CONCRETE_PAVING.get().defaultBlockState(), Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.TERRACOTTA_BLACK).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomSlabBlock> DARK_CONCRETE_PAVING_SLAB = BUILDING_BLOCK_REGISTRY.register("dark_concrete_paving_slab", () -> new CustomSlabBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.TERRACOTTA_BLACK).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomWallBlock> DARK_CONCRETE_PAVING_WALL = BUILDING_BLOCK_REGISTRY.register("dark_concrete_paving_wall", () -> new CustomWallBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.TERRACOTTA_BLACK).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomPressurePlateBlock> DARK_CONCRETE_PAVING_PRESSURE_PLATE = BUILDING_BLOCK_REGISTRY.register("dark_concrete_paving_pressure_plate", () -> new CustomPressurePlateBlock(BlockSetType.STONE, Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.TERRACOTTA_BLACK).noCollission().strength(1.5F, 6.0F), ToolTypes.PICKAXE));

    public static final DeferredBlock<CustomBlock> MOIST_PAVING = BUILDING_BLOCK_REGISTRY.register("moist_paving", () -> new CustomBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomStairBlock> MOIST_PAVING_STAIRS = BUILDING_BLOCK_REGISTRY.register("moist_paving_stairs", () -> new CustomStairBlock(MOIST_PAVING.get().defaultBlockState(), Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomSlabBlock> MOIST_PAVING_SLAB = BUILDING_BLOCK_REGISTRY.register("moist_paving_slab", () -> new CustomSlabBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomWallBlock> MOIST_PAVING_WALL = BUILDING_BLOCK_REGISTRY.register("moist_paving_wall", () -> new CustomWallBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomPressurePlateBlock> MOIST_PAVING_PRESSURE_PLATE = BUILDING_BLOCK_REGISTRY.register("moist_paving_pressure_plate", () -> new CustomPressurePlateBlock(BlockSetType.STONE, Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).noCollission().strength(1.5F, 6.0F), ToolTypes.PICKAXE));

    public static final DeferredBlock<CustomBlock> POLISHED_PAVING = BUILDING_BLOCK_REGISTRY.register("polished_paving", () -> new CustomBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomStairBlock> POLISHED_PAVING_STAIRS = BUILDING_BLOCK_REGISTRY.register("polished_paving_stairs", () -> new CustomStairBlock(POLISHED_PAVING.get().defaultBlockState(), Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomSlabBlock> POLISHED_PAVING_SLAB = BUILDING_BLOCK_REGISTRY.register("polished_paving_slab", () -> new CustomSlabBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomWallBlock> POLISHED_PAVING_WALL = BUILDING_BLOCK_REGISTRY.register("polished_paving_wall", () -> new CustomWallBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomPressurePlateBlock> POLISHED_PAVING_PRESSURE_PLATE = BUILDING_BLOCK_REGISTRY.register("polished_paving_pressure_plate", () -> new CustomPressurePlateBlock(BlockSetType.STONE, Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).noCollission().strength(1.5F, 6.0F), ToolTypes.PICKAXE));

    public static final DeferredBlock<CustomBlock> WHITE_CONCRETE_PAVING = BUILDING_BLOCK_REGISTRY.register("white_concrete_paving", () -> new CustomBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.TERRACOTTA_WHITE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomStairBlock> WHITE_CONCRETE_PAVING_STAIRS = BUILDING_BLOCK_REGISTRY.register("white_concrete_paving_stairs", () -> new CustomStairBlock(WHITE_CONCRETE_PAVING.get().defaultBlockState(), Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.TERRACOTTA_WHITE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomSlabBlock> WHITE_CONCRETE_PAVING_SLAB = BUILDING_BLOCK_REGISTRY.register("white_concrete_paving_slab", () -> new CustomSlabBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.TERRACOTTA_WHITE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomWallBlock> WHITE_CONCRETE_PAVING_WALL = BUILDING_BLOCK_REGISTRY.register("white_concrete_paving_wall", () -> new CustomWallBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.TERRACOTTA_WHITE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomPressurePlateBlock> WHITE_CONCRETE_PAVING_PRESSURE_PLATE = BUILDING_BLOCK_REGISTRY.register("white_concrete_paving_pressure_plate", () -> new CustomPressurePlateBlock(BlockSetType.STONE, Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.TERRACOTTA_WHITE).noCollission().strength(1.5F, 6.0F), ToolTypes.PICKAXE));

    // Tiles
    public static final Map<DyeColor, DeferredBlock<CustomBlock>> TILES_BLOCKS = Arrays.stream(DyeColor.values()).map(type -> Pair.of(type, BUILDING_BLOCK_REGISTRY.register(type.getName() + "_tiles", () -> new CustomBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(type.getMapColor()).strength(1.5F, 6.0F).sound(SoundType.STONE).requiresCorrectToolForDrops(), ToolTypes.PICKAXE)))).collect(Collectors.toMap(Pair::getKey, Pair::getValue));
    public static final Map<DyeColor, DeferredBlock<CustomStairBlock>> TILES_STAIRS = Arrays.stream(DyeColor.values()).map(type -> Pair.of(type, BUILDING_BLOCK_REGISTRY.register(type.getName() + "_tiles_stairs", () -> new CustomStairBlock(TILES_BLOCKS.get(type).get().defaultBlockState(), Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_BLACK).strength(1.5F, 6.0F).sound(SoundType.STONE).requiresCorrectToolForDrops(), ToolTypes.PICKAXE)))).collect(Collectors.toMap(Pair::getKey, Pair::getValue));
    public static final Map<DyeColor, DeferredBlock<CustomSlabBlock>> TILES_SLABS = Arrays.stream(DyeColor.values()).map(type -> Pair.of(type, BUILDING_BLOCK_REGISTRY.register(type.getName() + "_tiles_slab", () -> new CustomSlabBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(type.getMapColor()).strength(1.5F, 6.0F).sound(SoundType.STONE).requiresCorrectToolForDrops(), ToolTypes.PICKAXE)))).collect(Collectors.toMap(Pair::getKey, Pair::getValue));
    public static final Map<DyeColor, DeferredBlock<CustomWallBlock>> TILES_WALLS = Arrays.stream(DyeColor.values()).map(type -> Pair.of(type, BUILDING_BLOCK_REGISTRY.register(type.getName() + "_tiles_wall", () -> new CustomWallBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(type.getMapColor()).strength(1.5F, 6.0F).sound(SoundType.STONE).requiresCorrectToolForDrops(), ToolTypes.PICKAXE)))).collect(Collectors.toMap(Pair::getKey, Pair::getValue));
    public static final Map<DyeColor, DeferredBlock<CustomPressurePlateBlock>> TILES_PRESSURE_PLATES = Arrays.stream(DyeColor.values()).map(type -> Pair.of(type, BUILDING_BLOCK_REGISTRY.register(type.getName() + "_tiles_pressure_plate", () -> new CustomPressurePlateBlock(BlockSetType.STONE, Block.Properties.of().sound(SoundType.STONE).mapColor(type.getMapColor()).strength(1.5F, 6.0F).sound(SoundType.STONE).requiresCorrectToolForDrops(), ToolTypes.PICKAXE)))).collect(Collectors.toMap(Pair::getKey, Pair::getValue));

    public static final DeferredBlock<CustomBlock> CONCRETE_TILES = BUILDING_BLOCK_REGISTRY.register("concrete_tiles", () -> new CustomBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomStairBlock> CONCRETE_TILES_STAIRS = BUILDING_BLOCK_REGISTRY.register("concrete_tiles_stairs", () -> new CustomStairBlock(CONCRETE_TILES.get().defaultBlockState(), Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomSlabBlock> CONCRETE_TILES_SLAB = BUILDING_BLOCK_REGISTRY.register("concrete_tiles_slab", () -> new CustomSlabBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomWallBlock> CONCRETE_TILES_WALL = BUILDING_BLOCK_REGISTRY.register("concrete_tiles_wall", () -> new CustomWallBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomPressurePlateBlock> CONCRETE_TILES_PRESSURE_PLATE = BUILDING_BLOCK_REGISTRY.register("concrete_tiles_pressure_plate", () -> new CustomPressurePlateBlock(BlockSetType.STONE, Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).noCollission().strength(1.5F, 6.0F), ToolTypes.PICKAXE));

    public static final DeferredBlock<CustomBlock> SKYBLUE_TILES = BUILDING_BLOCK_REGISTRY.register("skyblue_tiles", () -> new CustomBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_LIGHT_BLUE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomStairBlock> SKYBLUE_TILES_STAIRS = BUILDING_BLOCK_REGISTRY.register("skyblue_tiles_stairs", () -> new CustomStairBlock(SKYBLUE_TILES.get().defaultBlockState(), Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_LIGHT_BLUE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomSlabBlock> SKYBLUE_TILES_SLAB = BUILDING_BLOCK_REGISTRY.register("skyblue_tiles_slab", () -> new CustomSlabBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_LIGHT_BLUE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomWallBlock> SKYBLUE_TILES_WALL = BUILDING_BLOCK_REGISTRY.register("skyblue_tiles_wall", () -> new CustomWallBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_LIGHT_BLUE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomPressurePlateBlock> SKYBLUE_TILES_PRESSURE_PLATE = BUILDING_BLOCK_REGISTRY.register("skyblue_tiles_pressure_plate", () -> new CustomPressurePlateBlock(BlockSetType.STONE, Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_LIGHT_BLUE).noCollission().strength(1.5F, 6.0F), ToolTypes.PICKAXE));

    public static final DeferredBlock<CustomBlock> YELLOW_GREY_TILES = BUILDING_BLOCK_REGISTRY.register("yellow_grey_tiles", () -> new CustomBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_YELLOW).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomStairBlock> YELLOW_GREY_TILES_STAIRS = BUILDING_BLOCK_REGISTRY.register("yellow_grey_tiles_stairs", () -> new CustomStairBlock(YELLOW_GREY_TILES.get().defaultBlockState(), Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_YELLOW).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomSlabBlock> YELLOW_GREY_TILES_SLAB = BUILDING_BLOCK_REGISTRY.register("yellow_grey_tiles_slab", () -> new CustomSlabBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_YELLOW).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomWallBlock> YELLOW_GREY_TILES_WALL = BUILDING_BLOCK_REGISTRY.register("yellow_grey_tiles_wall", () -> new CustomWallBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_YELLOW).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomPressurePlateBlock> YELLOW_GREY_TILES_PRESSURE_PLATE = BUILDING_BLOCK_REGISTRY.register("yellow_grey_tiles_pressure_plate", () -> new CustomPressurePlateBlock(BlockSetType.STONE, Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.COLOR_YELLOW).noCollission().strength(1.5F, 6.0F), ToolTypes.PICKAXE));

    // Wallpapers
    public static final DeferredBlock<CustomBlock> WHITE_BLUE_WALLPAPER = BUILDING_BLOCK_REGISTRY.register("white_blue_wallpaper", () -> new CustomBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomStairBlock> WHITE_BLUE_WALLPAPER_STAIRS = BUILDING_BLOCK_REGISTRY.register("white_blue_wallpaper_stairs", () -> new CustomStairBlock(WHITE_BLUE_WALLPAPER.get().defaultBlockState(), Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomSlabBlock> WHITE_BLUE_WALLPAPER_SLAB = BUILDING_BLOCK_REGISTRY.register("white_blue_wallpaper_slab", () -> new CustomSlabBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<UpDownBlock> WHITE_BLUE_WALLPAPER_PLINTH = BUILDING_BLOCK_REGISTRY.register("white_blue_wallpaper_plinth", () -> new UpDownBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));

    public static final DeferredBlock<CustomBlock> BEIGE_FLOWER_WALLPAPER = BUILDING_BLOCK_REGISTRY.register("beige_flower_wallpaper", () -> new CustomBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomStairBlock> BEIGE_FLOWER_WALLPAPER_STAIRS = BUILDING_BLOCK_REGISTRY.register("beige_flower_wallpaper_stairs", () -> new CustomStairBlock(BEIGE_FLOWER_WALLPAPER.get().defaultBlockState(), Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomSlabBlock> BEIGE_FLOWER_WALLPAPER_SLAB = BUILDING_BLOCK_REGISTRY.register("beige_flower_wallpaper_slab", () -> new CustomSlabBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<UpDownBlock> BEIGE_FLOWER_WALLPAPER_PLINTH = BUILDING_BLOCK_REGISTRY.register("beige_flower_wallpaper_plinth", () -> new UpDownBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));

    public static final DeferredBlock<CustomBlock> BEIGE_WALLPAPER = BUILDING_BLOCK_REGISTRY.register("beige_wallpaper", () -> new CustomBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomStairBlock> BEIGE_WALLPAPER_STAIRS = BUILDING_BLOCK_REGISTRY.register("beige_wallpaper_stairs", () -> new CustomStairBlock(BEIGE_WALLPAPER.get().defaultBlockState(), Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomSlabBlock> BEIGE_WALLPAPER_SLAB = BUILDING_BLOCK_REGISTRY.register("beige_wallpaper_slab", () -> new CustomSlabBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<UpDownBlock> BEIGE_WALLPAPER_PLINTH = BUILDING_BLOCK_REGISTRY.register("beige_wallpaper_plinth", () -> new UpDownBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));

    public static final DeferredBlock<CustomBlock> PINK_WALLPAPER = BUILDING_BLOCK_REGISTRY.register("pink_wallpaper", () -> new CustomBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomStairBlock> PINK_WALLPAPER_STAIRS = BUILDING_BLOCK_REGISTRY.register("pink_wallpaper_stairs", () -> new CustomStairBlock(PINK_WALLPAPER.get().defaultBlockState(), Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomSlabBlock> PINK_WALLPAPER_SLAB = BUILDING_BLOCK_REGISTRY.register("pink_wallpaper_slab", () -> new CustomSlabBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<UpDownBlock> PINK_WALLPAPER_PLINTH = BUILDING_BLOCK_REGISTRY.register("pink_wallpaper_plinth", () -> new UpDownBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));

    public static final DeferredBlock<CustomBlock> WHITE_GREEN_WALLPAPER = BUILDING_BLOCK_REGISTRY.register("white_green_wallpaper", () -> new CustomBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomStairBlock> WHITE_GREEN_WALLPAPER_STAIRS = BUILDING_BLOCK_REGISTRY.register("white_green_wallpaper_stairs", () -> new CustomStairBlock(WHITE_GREEN_WALLPAPER.get().defaultBlockState(), Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<CustomSlabBlock> WHITE_GREEN_WALLPAPER_SLAB = BUILDING_BLOCK_REGISTRY.register("white_green_wallpaper_slab", () -> new CustomSlabBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));
    public static final DeferredBlock<UpDownBlock> WHITE_GREEN_WALLPAPER_PLINTH = BUILDING_BLOCK_REGISTRY.register("white_green_wallpaper_plinth", () -> new UpDownBlock(Block.Properties.of().sound(SoundType.STONE).mapColor(MapColor.STONE).strength(1.5F, 6.0F), ToolTypes.PICKAXE));

    // Stairs
    public static final Map<McWoods, DeferredBlock<SuspendedStairBlock>> SUSPENDED_STAIRS_BLOCKS = Arrays.stream(McWoods.values()).map(type -> Pair.of(type, BUILDING_BLOCK_REGISTRY.register(type.getSerializedName() + "_suspended_stairs", () -> new SuspendedStairBlock(Block.Properties.of().sound(SoundType.WOOD).mapColor(MapColor.WOOD).strength(3.0F).noOcclusion(), ToolTypes.AXE, false)))).collect(Collectors.toMap(Pair::getKey, Pair::getValue));
    public static final Map<McWoods, DeferredBlock<SuspendedStairBlock>> LARGE_SUSPENDED_STAIRS_BLOCKS = Arrays.stream(McWoods.values()).map(type -> Pair.of(type, BUILDING_BLOCK_REGISTRY.register(type.getSerializedName() + "_large_suspended_stairs", () -> new SuspendedStairBlock(Block.Properties.of().sound(SoundType.WOOD).mapColor(MapColor.WOOD).strength(3.0F).noOcclusion(), ToolTypes.AXE, true)))).collect(Collectors.toMap(Pair::getKey, Pair::getValue));

    // Doors
    public static final Map<McWoods, DeferredBlock<CustomDoorBlock>> FANCY_DOOR_BLOCKS = Arrays.stream(McWoods.values()).map(type -> Pair.of(type, BUILDING_BLOCK_REGISTRY.register(type.getSerializedName() + "_fancy_door", () -> new CustomDoorBlock(type.getType(), Block.Properties.of().sound(SoundType.WOOD).mapColor(MapColor.WOOD).strength(3.0F).noOcclusion(), ToolTypes.AXE)))).collect(Collectors.toMap(Pair::getKey, Pair::getValue));
    public static final Map<McWoods, DeferredBlock<CustomDoorBlock>> PLAIN_DOOR_BLOCKS = Arrays.stream(McWoods.values()).map(type -> Pair.of(type, BUILDING_BLOCK_REGISTRY.register(type.getSerializedName() + "_plain_door", () -> new CustomDoorBlock(type.getType(), Block.Properties.of().sound(SoundType.WOOD).mapColor(MapColor.WOOD).strength(3.0F).noOcclusion(), ToolTypes.AXE)))).collect(Collectors.toMap(Pair::getKey, Pair::getValue));
}
